apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-11-04T13:46:57Z"
  labels:
    app: ro-svc
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":8180,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2020-11-04T13:46:57Z"
  name: ro-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/ro-svc
  uid: be722820-0917-4501-ad05-e1273f76248b
spec:
  ports:
  - name: 8180-8080
    port: 8180
    protocol: TCP
    targetPort: 8080
  selector:
    app: dep-demo
  sessionAffinity: None
  type: ClusterIP
